import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from '@/components/Navbar';
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <SessionWrapper>
          <Navbar />
          <hr />
          {children}
          <hr />
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
